### ISSUE TITLE
Change all code snippets in *.tex to follow the LLVM coding style

### ISSUE THREAD

**Issue by Szelethus** [Szelethus/ELTE-IK-CPP#4]

**Comment by Szelethus** [comment]
This could be implemented with a short script that would use `clang-format` on all code snippets. This script could be placed in a `utils` directory for later use.

**Comment by steakhal** [comment]
The auto formatter script has been added in commit: e70689c 

**I still recommend not to use** it, becouse the tool **cannot distinguish** **C++ code** snippets from **Bash** and other kind of snippets.

You can identify these running the script and than using the `git diff` command, to see the changes.

**Comment by steakhal** [comment]
The script in commit: d374d83 **will do the formatting as C++ code** if:
- **no attributes** are given (absolutely none)
- **style** attribute is **C++**
- **language** attribute is **C++**

Only for _.tex_ files in _../book_ and _../exercise_ folders.

**Comment by Szelethus** [comment]
Excellent! Very well done! I'm very pleased with how things are looking, thank you :)
