### ISSUE TITLE
Use a different tag for non-cpp snippets.

### ISSUE THREAD

**Issue by steakhal** [Szelethus/ELTE-IK-CPP#5]
Worth using different style tags for **different** code snippets in tex file.
Especially for C++ code, to be able to automatically reformat all **C++ snippets**.

This problem occurs regulary in the codebase.

- https://github.com/Szelethus/ELTE-IK-CPP/blob/c9a1f690e11cd50ca7e6100f45c525cc66b31429/book/01gy_cpp/01gy_cpp.tex#L155
- https://github.com/Szelethus/ELTE-IK-CPP/blob/c9a1f690e11cd50ca7e6100f45c525cc66b31429/book/01gy_cpp/01gy_cpp.tex#L172
- https://github.com/Szelethus/ELTE-IK-CPP/blob/c9a1f690e11cd50ca7e6100f45c525cc66b31429/book/01gy_cpp/01gy_cpp.tex#L176
- https://github.com/Szelethus/ELTE-IK-CPP/blob/c9a1f690e11cd50ca7e6100f45c525cc66b31429/book/01gy_cpp/01gy_cpp.tex#L459

and many more...

I can see that you are using _[style = customasm]_ attribute for assembly snippets, are there any for **bash** too?

**Comment by steakhal** [comment]
We should mark the language explicitly in all snippets (or we can implicitly fall back to C++ if no language set) in all tex files.

Working example:
```latex
\begin{lstlisting}[language=c++]
int factorial(int n) {
  if (n <= 0) return 1;
  else return n*factorial(n-1);
}
\end{lstlisting}

\begin{lstlisting}[language=bash]
#!/bin/bash
echo "Hello, world!"
\end{lstlisting}
```

**Comment by Szelethus** [comment]
Nice catch! Never noticed that bash scripts don't have anything that would indicate that they are in fact not C++ or assembly code snippets.

**Comment by steakhal** [comment]
Added **customcpreproc** style in _preambulum_.

This style should be used, if the code should not reformatted (eg. when showing the wrong usages of preprocessor directives).

It is important to leave the spaces before PP directives, to show that use-case too...

So I have done these in commit: d374d83

**Comment by Szelethus** [comment]
LGTM, good job!
